### ISSUE TITLE
Unreadable text with light theme

### ISSUE THREAD

**Issue by wavebeem** [steelbrain/linter#1234] opened 2016-09-04 17:49 UTC
Linter v1.11.16 (macOS and Windows)

Text color is unreadable in editor tooltip with a light theme.

I expected the tooltip badge text color to always be white since it always uses a dark background, regardless of light/dark editor theme.

![image](https://cloud.githubusercontent.com/assets/176815/18232831/060d1996-728d-11e6-8c93-2e3ec0503ac1.png)

P.S. Awesome project! Best linter integration I've ever tried :smiley:

**Comment by steelbrain** [comment] 2016-09-04 19:23
@Arcanemagus ^ looks like an eslint issue

**Comment by wavebeem** [comment] 2016-09-04 19:24
Sorry, I'm not familiar with which package manages which part.

**Comment by steelbrain** [comment] 2016-09-04 19:25
@wavebeem It's fine, I was just pinging @Arcanemagus in this issue because he manages the linter in question

**Comment by Arcanemagus** [comment] 2016-09-09 17:44
It actually uses the colors from the theme, and as your screenshot shows, some are _terrible_ at picking colors that work for anything other than their own use.

I'm thinking of just forcing specific colors and ignoring the user's theme.

**Comment by wavebeem** [comment] 2016-09-09 17:54
> I'm thinking of just forcing specific colors and ignoring the user's theme.

That sounds like a good idea to me. Probably the best way to make it resilient to the countless themes for Atom.

**Comment by steelbrain** [comment] 2016-10-03 23:43
Closing as external, feel free to continue discussion

**Closed by steelbrain** 2016-10-03 23:43 UTC
Labels: external

**Comment by wavebeem** [comment] 2016-10-03 23:44
@steelbrain So is this something I should file against a different project? Such as linter-eslint or the One Light theme?

**Comment by steelbrain** [comment] 2016-10-03 23:44
linter-eslint is the one you're looking for (I think)

**Comment by Arcanemagus** [comment] 2016-10-03 23:52
Specifically it's a duplicate of https://github.com/AtomLinter/linter-eslint/issues/482.
