### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMarker' of undefined

### ISSUE THREAD

**Issue by davepeck** [steelbrain/linter#1212] opened 2016-08-04 18:09 UTC
Unfortunately I have yet to find a simple repro case. I'll keep looking.

I wouldn't be surprised if this were related to https://github.com/atom/atom/issues/12111

**Atom Version**: 1.9.2
**System**: Mac OS X 10.11.6
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.14

### Stack Trace

Uncaught TypeError: Cannot read property 'getMarker' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:194

TypeError: Cannot read property 'getMarker' of undefined
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:194:65)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1528:37)
    at /Users/dave/.atom/packages/linter/lib/editor-linter.js:59:21
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/dave/.atom/packages/linter/lib/editor-linter.js:143:20)
    at /Users/dave/.atom/packages/linter/lib/linter-views.js:111:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/dave/.atom/packages/linter/lib/linter-views.js:109:11)
    at LinterViews.render (/Users/dave/.atom/packages/linter/lib/linter-views.js:58:10)
    at /Users/dave/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/dave/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/dave/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -2:23.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -2:18.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:30 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  2x -0:28.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:24.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:21.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:14.7.0 pane:split-right-and-copy-active-item (atom-text-editor.editor)
     -0:10.4.0 core:close (atom-text-editor.editor)
     -0:08.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.1.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:03.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-python-pyflakes",
      "symbols-view",
      "linter-jscs",
      "atom-beautify",
      "markdown-scroll-sync",
      "autocomplete-python"
    ],
    "followSymlinks": false,
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "*.png",
      "*.jpg",
      "*.pyc",
      "tags",
      "_site"
    ]
  },
  "linter": {
    "lintOnChange": true,
    "statusBar": "Show all errors",
    "subtleLinterErrors": [
      "flake8"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined (inactive)
atom-ctags, v4.5.2 (active)
atom-jade, v0.3.0 (active)
atom-ternjs, v0.14.2 (active)
autocomplete-clang, v0.9.4 (active)
autocomplete-python, v1.8.4 (inactive)
django-templates, v0.5.0 (active)
editorconfig, v1.4.1 (active)
git-plus, v5.16.2 (inactive)
hex, v0.6.2 (active)
insert-timestamp, v0.2.4 (inactive)
language-coffee-script, v0.46.0 (active)
language-gradle, v0.0.3 (active)
language-haskell, v1.7.18 (active)
language-swift, v0.4.0 (active)
linter, v1.11.14 (active)
linter-flake8, v1.13.2 (active)
linter-jscs, v4.0.5 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
project-manager, v2.9.7 (active)
set-syntax, v0.3.0 (active)
solarized-dark-ui, v0.3.1 (inactive)
solarized-light-ui, v0.1.0 (inactive)
switch-header-source, v0.20.0 (inactive)
twilight, v0.3.0 (inactive)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.46.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-08-04 18:21
Dupe of #1210

**Closed by steelbrain** 2016-08-04 18:21 UTC
