### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by vladgohn** [steelbrain/linter#1161] opened 2016-05-27 17:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/vladgohn/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/vladgohn/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:02.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-live-server, v1.2.5
bemhtml, v0.10.0
color-picker, v2.1.1
file-icons, v1.7.12
jshint, v1.8.5
language-babel, v2.23.2
language-dot, v1.6.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-jade, v0.3.2
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-jsonlint, v1.2.5
linter-markdownlint, v1.0.1
linter-php, v1.2.0
linter-scss-lint, v3.0.4
pigments, v0.27.1
react, v0.15.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-05-27 17:39
Duplicate of #1054.

**Closed by Arcanemagus** 2016-05-27 17:39 UTC
