### ISSUE TITLE
Allow user to change search engine

### ISSUE THREAD

**Issue by rugk** [steelbrain/linter#1387] opened 2017-03-21 19:53 UTC
Please allow the user to change the search engine sometimes used as a "link" on linter messages. Not everyone likes Google…

An option to enter the parametrized URL `https://duckduckgo.com/?q=%s` would be enough.

**Comment by steelbrain** [comment] 2017-03-21 19:56
Dupe off https://github.com/steelbrain/linter-ui-default/issues/213

**Closed by steelbrain** 2017-03-21 19:56 UTC
