### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by itsnydell** [steelbrain/linter#1155] opened 2016-05-19 15:13 UTC
1. Opened the linter-less settings. 
2. Toggled "ignore Undefined Global Variables" on and then off
3. Toggled "ignore undefined variables" on and then off
4. Clicked a line with less error and got this error:

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/.../.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/.../.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
  2x -2:40.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:39.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:39.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:36.9.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -2:35 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -2:33.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:26.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:25 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:23 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:22.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  9x -0:21.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  9x -0:19.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:12.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:11 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:11 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "wrap-guide"
    ],
    "projectHome": "/mnt/httpd2/htdocs/",
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
file-icons, v1.7.11
firewatch-syntax, v1.0.1
language-babel, v2.20.8
linter, v1.11.4
linter-less, v2.5.0
linter-scss-lint, v3.0.3
minimap, v4.23.5
pigments, v0.26.3
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-05-19 16:42
Duplicate of #1054.

**Closed by Arcanemagus** 2016-05-19 16:42 UTC
Labels: duplicate
