### ISSUE TITLE
Error while running ESLint: Unexpected token } in JSON at position 424.

### ISSUE THREAD

**Issue by createdbyjurand** [steelbrain/linter#1558] opened 2017-11-03 01:28 UTC
Issue Type BUG

Issue Description

I use Atom to verify js code.
I use linter-eslint 8.4.0
I use linter 2.2.0
I got first line on top underline red with this info.
I reinstalled all packages with yarn (before it was npm) - thought it could be some old dependiency.

.eslint config:
{
"plugins": [ "react" ],
"extends": [ "eslint:recommended" ],
"env": {
"es6": true,
"browser": true,
"node": true,
"jquery": true
},
"rules": { "strict": "off" },
"parserOptions": {
"ecmaVersion": 6,
"sourceType": "module",
"ecmaFeatures": { "jsx": true }
}
}

Bug Checklist
Linter (bottom slide menu of atom) gives the same error.

**Comment by Arcanemagus** [comment] 2017-11-03 03:44
Duplicate of https://github.com/AtomLinter/linter-eslint/issues/1045

**Closed by Arcanemagus** 2017-11-03 03:44 UTC
