### ISSUE TITLE
Unknown Error after Recent Update

### ISSUE THREAD

**Issue by JLCCI** [steelbrain/linter#1393] opened 2017-03-23 06:55 UTC
After updating the linter today I started getting a weird message span - not sure how to get the details but around 6-7 message popups appear after which they all disappear. The linter is working fine and the messages stop appearing for another 30-40 min.

![screenshot from 2017-03-23 15-52-46](https://cloud.githubusercontent.com/assets/18163728/24235512/fac76aa4-0fe0-11e7-8225-6cdc6c915192.png)

Sorry for bad screenshot, I had to do it quickly. I had an open Python file with Hydrogen plugin running.

**Comment by steelbrain** [comment] 2017-03-23 10:40
Dupe of https://github.com/steelbrain/linter/issues/1369

Fixed in latest release

**Closed by steelbrain** 2017-03-23 10:40 UTC
