### ISSUE TITLE
Error spawn /usr/lib/node_modules/atom-package-manager/bin/node ENOENT

### ISSUE THREAD

**Issue by Hativ3** [steelbrain/linter#1476] opened 2017-05-29 09:37 UTC
If opening normal files, e.g. .txt, .log, .xml where I have no linter-plugin installed I get the following error message:

> Failed to run undefined undefined
> spawn /usr/lib/node_modules/atom-package-manager/bin/node
> ENOENT

Image: http://i.imgur.com/U3oeEzM.png

No entry in developer console.

I identified linter as issue by disabling and re-enabling all plugins.

**Comment by steelbrain** [comment] 2017-05-29 09:40
Hi @Hativ3

The problem is fixed by disabling Linter because Linter is the package that invokes other packages. If you disable linter, while keeping the faulty package enabled, that package will never be invoked and you'll think that the error is fixed.

Can you post the output of `Linter: Debug` command?

**Comment by Hativ3** [comment] 2017-05-29 09:53
> Can you post the output of Linter: Debug command?

How do I do that?

**Comment by Hativ3** [comment] 2017-05-29 09:59
Ok, I identified the right package. linter-write-good is causing this. Sorry for the trouble.

**Closed** 2017-05-29 10:01 UTC
Labels: external, unconfirmed bug
