### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by dcrystalj** [steelbrain/linter#1318] opened 2017-02-12 08:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [linter](https://github.com/atom-community/linter) package 1.11.21

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189

TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189:34)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (/app.asar/node_modules/text-buffer/lib/marker.js:269:18)
    at /packages/linter/lib/editor-linter.js:75:35
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at EditorLinter.deleteMessage (/packages/linter/lib/editor-linter.js:151:20)
    at /packages/linter/lib/linter-views.js:106:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/packages/linter/lib/linter-views.js:104:13)
    at LinterViews.render (/packages/linter/lib/linter-views.js:58:10)
    at /packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MessageRegistry.updatePublic (/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -2:32.2.0 core:select-up (input.hidden-input)
     -2:31.8.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:31.3.0 core:copy (input.hidden-input)
     -1:54.3.0 core:save (input.hidden-input)
  3x -1:31.3.0 core:delete (input.hidden-input)
  7x -1:30.3.0 core:move-left (input.hidden-input)
     -1:29 core:delete (input.hidden-input)
  2x -1:28.4.0 core:save (input.hidden-input)
     -1:20.8.0 find-and-replace:select-next (input.hidden-input)
     -1:20.6.0 core:backspace (input.hidden-input)
     -1:20.2.0 core:save (input.hidden-input)
     -0:45.7.0 core:backspace (input.hidden-input)
     -0:42.2.0 core:delete (input.hidden-input)
  3x -0:40.6.0 core:save (input.hidden-input)
     -0:11.7.0 find-and-replace:show (input.hidden-input)
     -0:10.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
accents-ui 1.2.0 
aligner 0.22.3 
an-color-picker 1.0.2 
an-old-hope-syntax 1.0.1 
atom-bracket-highlight 0.3.2 
atom-brackets-glow 0.4.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.47 
calculate 0.3.4 
close-tags 0.6.0 
color-picker 2.2.5 
count-word 0.2.3 
dracula-theme 2.0.0 
dracula-ui 0.4.1 
es6-javascript 1.0.0 
eval-javascript 1.2.0 
genesis-ui 0.5.0 
gist 0.3.1 
git-plus 7.2.2 
git-time-machine 1.5.4 
gpp-compiler 3.0.7 
hidpi 0.12.0 
highlight-selected 0.12.0 
increment-selection 0.3.0 
javascript-snippets 1.2.1 
jsartisan-dark-minimalistic-ui 2.3.0 
language-blade 0.27.1 
language-latex 1.0.0 
language-lisp 0.2.0 
language-todotxt 0.6.1 
language-vue 0.21.2 
laravel-forms-bootstrap-snippets 1.2.0 
latex 0.42.3 
latex-autocomplete 1.0.0 
lint 0.0.1 
linter 1.11.21 
linter-clang 3.4.6 
linter-jshint 3.0.2 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.0 
linter-pylama 0.8.13 
linter-pylint 1.2.2 
linter-python 3.0.5 
lucid-tabs 1.1.1 
open-recent 5.0.0 
pane-manager 1.0.1 
pdf-view 0.54.0 
pigments 0.39.0 
pinned-tabs 0.4.2 
process-palette 0.11.0 
quick-editor 0.4.3 
script 3.14.1 
select-rectangle 1.0.2 
set-syntax 0.3.2 
sourcerer 2.0.0 
Spectacular 1.1.0 
sync-settings 0.8.1 
tab-control 0.6.9 
tabs-closer 0.14.0 
tabs-to-spaces 1.0.3 
tasks 2.6.6 
terminal-plus 0.14.5 
toggle-markdown-task 0.6.0 
vue-snippets 0.6.0 
webbox-color 0.5.9 
```

**Comment by steelbrain** [comment] 2017-02-12 08:24
Dupe of steelbrain/linter-ui-default#41
bug in Atom

**Closed by steelbrain** 2017-02-12 08:24 UTC
