### ISSUE TITLE
Linter status bar when no language is installed?

### ISSUE THREAD

**Issue by linickx** [steelbrain/linter#1153] opened 2016-05-17 08:57 UTC
Hi,

Within the settings we can enable/disable `Display Linter Status Info in Status Bar`. 

Would it possible to hide,disable, or change "No Issues" when no language (linter) is installed, e.g..

- `Test.py` - linter-python installed, found errors/warnings - status bar => X Issues
- `Test.sh` - linter-shellchek installed, no errors/warning - status bar => No Issues
- `Test.js` - No linter installed - status bar => ???

In the current implementation, the status bar would say "No Issues" for `Test.js` which might not actually be true. My preference would be to hide the pane, but other users might want to see a "no linter" warning.

Thx!

**Comment by steelbrain** [comment] 2016-05-17 15:08
Don't you think hiding and showing everytime you switch a tab that has a linter and a tab that has not would be annoying in terms of UX?

**Comment by linickx** [comment] 2016-05-17 15:17
No, as I expect the status bar to be context appropriate and show/hide the information that is relevant to the file I am viewing. 

An example of existing precedence is: If you start atom from a git enabled folder, the current branch is shown in the status bar; if you then open a new file (_same window, in a new tab_) that is from a different folder (_i.e. non-git-enabled_) the branch indicator disappears.

**Comment by linickx** [comment] 2016-05-17 15:28
![atom-linter-example](https://cloud.githubusercontent.com/assets/649661/15328276/35547a7e-1c4c-11e6-907e-2071978fad68.gif)

Gif for existing precedence, keep an eye on the bottom right  😊

**Comment by steelbrain** [comment] 2016-05-17 15:39
I suppose we could implement this after some votes

**Comment by linickx** [comment] 2016-05-17 15:46
👍 😉

**Comment by oli-obk** [comment] 2016-05-18 12:17
:-1: I use `linter` together with `build`, which works on projects, not files. So it can give lints for arbitrary files, even some that don't have linters installed. What would be the expected behaviour in case lints are reported for such files?

**Comment by linickx** [comment] 2016-05-18 12:44
> So it can give lints for arbitrary files, even some that don't have linters installed

What do you mean by this? Surely even for build what is actually happening is the lint for arbitrary files is "no issue" which is convenient but not necessarily accurate?

> What would be the expected behaviour in case lints are reported for such files?

Project status should remain as 'No issues' . i.e. the net result of all the files that can be checked.

The purpose of the feature request was to remove the false positive of stating that non-linter files are without issue, not to break workflow.

**Comment by oli-obk** [comment] 2016-05-18 12:53
> Surely even for build what is actually happening is the lint for arbitrary files is "no issue" which is convenient but not necessarily accurate?

`build` produces lints from the output of a command. If the output contains something saying that there's an error in a file, then `build` creates a lint for that statement. If there's no statement, it doesn't do anything. So there's no way to distinguish between a file that has no issues and a file that wasn't tested.

> stating that non-linter files are without issue

I don't see how that can be detected in the general case.

**Comment by linickx** [comment] 2016-05-18 12:56
> So there's no way to distinguish between a file that has no issues and a file that wasn't tested.

>> stating that non-linter files are without issue

> I don't see how that can be detected in the general case.

Bummer, that sounds like a blocker then 😞

**Comment by fny** [comment] 2016-05-30 13:46
I really, really like the idea of having "No Linter"/"Not Linted" instead of "No Issues" when a linter is missing. Hopping between computers and editors, I've forgotten to install a linter and made a dirty commit every now and then... Not sure I like the idea of having another dedicated status bar item since that real estate is precious.

@oli-obk, I actually think this would be a fantastic feature to use with `build`. If you've built the file recently, it has "no issues." If you haven't, it's "not linted."

**Comment by steelbrain** [comment] 2016-08-28 00:01
Done (not yet released, but closing anyway to keep only unresolved issues open for easy view)

The way this is done is that we've added a busy-signal at the bottom, it spins when a linter is triggered and keeps spinning until it finishes. If there's no linter it doesn't spin at all

**Closed by steelbrain** 2016-08-28 00:01 UTC
Labels: feature request, requesting votes

**Comment by linickx** [comment] 2016-08-28 13:26
🆒
