### ISSUE TITLE
Option to disable Markdown parser

### ISSUE THREAD

**Issue by lierdakil** [steelbrain/linter#1389] opened 2017-03-22 10:32 UTC
Well, I tried switching to v2. I couldn't. Not without some hoop-jumping anyway.

I love Markdown. But compiler (from which I get my messages) doesn't talk Markdown, it talks utf-8 with weird tabulations (and before you ask, no, those are meaningful and will have to stay).

So would be nice if it was possible to provide good-old plaintext in the `description`, otherwise, this happens:
![image](https://cloud.githubusercontent.com/assets/7275622/24193477/6fdb12de-0f03-11e7-91d0-af886a8007f6.png)

Also I would argue accepting good-old HTML would've been better, because, you know, very few linters out there output Markdown actually, and it's not designed to be written programmatically, but what do I know.

**Comment by Arcanemagus** [comment] 2017-03-22 22:09
> very few linters out there output Markdown actually

This isn't really relevant as I don't know any that output (usable) HTML either, but that's besides the point 😛.

I can definitely see merit to this suggestion, as a temporary workaround can you wrap what you are trying to put in the `description` in \`\`\`?

**Comment by lierdakil** [comment] 2017-03-22 22:34
> I don't know any that output (usable) HTML either

True. But HTML is easier to generate in (sudo) browser environment, so if you want rich formatting, HTML makes more sense then Markdown IMO. Latter will eventually be converted into former anyway. But, as you say, beside the point.

>  can you wrap what you are trying to put in the description in ```?

Wrapping in ``` or ~~~ will make it look exactly like second line in the screenshot above, no? This sorta defeats the purpose. I could of course try to hack around that with some css, but that's exactly what I call hoop-jumping.

**Comment by Arcanemagus** [comment] 2017-03-22 23:37
> make it look exactly like second line in the screenshot above, no?

Unfortunately yes 😞.

**Comment by steelbrain** [comment] 2017-03-30 21:40
Copy-pasted from https://github.com/steelbrain/linter/issues/1407#issuecomment-290548844
--

There's definitely a usecase where you want to preserve whitespace in your description. You don't necessarily need HTML for that, for example you can just do this in description
```js
{
  // ... other props ...
  description: `<pre class="my-linter-preserve-format">Insert\n pre\n formatted\n text\n here</pre>`,
}
```
and then you can add this to your package stylesheet
```css
.my-linter-preserve-format {
  /* override background inherit of <pre> md tag */
  background: inherit;
}
```

**Comment by lierdakil** [comment] 2017-04-03 03:36
> I could of course try to hack around that with some css, but that's exactly what I call hoop-jumping.

> and then you can add this to your package stylesheet

You know, it's kinda strange to ask users to hack *around* your design. Not good UX by any stretch, is it?

I have to admit that I'm getting increasingly frustrated with this exchange for some reason. So sorry in advance.

**Comment by steelbrain** [comment] 2017-04-03 04:10
When somebody takes the time to open an issue on this repo, I value their request, and I especially value yours because of the history we share. But as I said, when you have a diverse userbase you have to make certain decisions that displease a few people, but I have tried and presented you with a workaround that's not too complicated and sounds totally reasonable to me and is straight forward without any regressions that I can think of.

Furthermore, it's just a one time thing, you have to write those three lines of css and forget about it. On the other hand, I will have to add a whole parameter to the message object, add it's validation in linter, support it in the UI (and every other UI package that gets created in the future will have to support it).

I am not trying to be rude or dismissive, I apologize if it came off like that :)

**Comment by steelbrain** [comment] 2017-06-02 18:17
Update, @lloiser hit this while working on a flow-ide PR.

We wanted to preserve the whitespace while still adding links into content and without any css hacks, he found out that wrapping contents in `<div style="white-space: pre-wrap">`  instead of `<pre>` preserved the whitespace without the code-block styling while allowing inner links to be rendered perfectly.

Closing as this is a reasonably good resolution to the original issue. Feel free to continue discussing.

**Closed** 2017-06-02 18:24 UTC
Labels: meta
