### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by mnzt** [steelbrain/linter#1157] opened 2016-05-20 11:25 UTC
[Enter steps to reproduce below:]

1. Click on an issue to view the details

**Atom Version**: 1.7.3
**System**: linux 4.5.1-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/usr/share/atom/resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/share/atom/resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/home/mnzt/.atom/packages/linter/lib/linter-views.js:86:43)
    at /home/mnzt/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:30.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:30.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:30.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:30.2.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:30.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:29.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:14.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:14 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:03.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:02.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.8.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-outlander-syntax.theme-dark-flat-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "environment"
    ],
    "themes": [
      "dark-flat-ui",
      "outlander-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 24
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
autocomplete-go, v1.1.0
builder-go, v1.0.0
color-picker, v2.1.1
dark-flat-ui, v1.2.4
express-complete, v0.2.0
glow, v0.3.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
linter-jsonlint, v1.2.5
navigator-godef, v1.0.3
outlander-syntax, v1.1.0
pretty-json, v1.2.
react, v0.15.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-05-20 11:42
Dupe of #1054

**Closed by steelbrain** 2016-05-20 11:42 UTC
