### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by VincentGuinaudeau** [steelbrain/linter#1139] opened 2016-04-24 17:04 UTC
[Enter steps to reproduce below:]

1. i don't really now, this error just show as I was typing in the editor

**Atom Version**: 1.7.2
**System**: Ubuntu 14.04.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/local/share/atom/resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/usr/local/share/atom/resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/local/share/atom/resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/home/guinau_v/.atom/packages/linter/lib/linter-views.js:86:43)
    at /home/guinau_v/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
  2x -0:50.7.0 core:move-up (atom-text-editor.editor.power-mode.is-focused)
  2x -0:50.3.0 core:move-down (atom-text-editor.editor.power-mode.is-focused)
     -0:30.4.0 tree-view:toggle (atom-text-editor.editor.power-mode.is-focused)
 24x -0:29.7.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:28 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 18x -0:27.6.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:26 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 10x -0:25.3.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.9.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:22.4.0 tree-view:toggle (atom-text-editor.editor.power-mode.is-focused)
  2x -0:18.4.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 22x -0:17.8.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:16.4.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.9.0 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.1.0 tree-view:toggle (atom-text-editor.editor.power-mode.is-focused)
     -0:03.9.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autoflow",
      "metrics",
      "welcome",
      "spell-check",
      "minimap-autohide",
      "wrap-guide",
      "project-view",
      "autohide-tree-view",
      "hide-tree",
      "gutter-shadow"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "minimap-highlight-selected"
    ],
    "themes": [
      "atom-material-ui",
      "monokai-seti"
    ]
  },
  "linter": {
    "errorPanelHeight": 67,
    "lintOnFlyInterval": 500
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.4.1
atom-beautify, v0.29.6
atom-material-ui, v1.2.10
color-tabs, v0.1.8
epitools, v0.4.1
fonts, v1.2.0
git-control, v0.7.1
git-plus, v5.13.4
highlight-selected, v0.11.2
keyboard-localization, v1.4.18
language-ocaml, v1.1.2
language-x86, v1.0.1
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-gcc, v0.6.9
linter-jshint, v2.1.0
minimap, v4.22.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
monokai-seti, v0.7.0
multi-cursor, v2.1.3
project-plus, v0.8.2
release-notes, v0.53.0
remote-sync, v4.0.1
seti-icons, v0.4.5
sync-settings, v0.7.2
tree-view-git-branch, v0.1.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-04-24 18:28
Dupe of #1054

**Closed by steelbrain** 2016-04-24 18:28 UTC
