### ISSUE TITLE
With linter 2.1.0 multiple pylint processes are spawned even though only one file is modified

### ISSUE THREAD

**Issue by marmistrz** [steelbrain/linter#1376] opened 2017-03-18 09:42 UTC
And the laptop fan gets really loud...

Probably the linter wants to scan the whole projects, which is not always a good idea.

This may be a problem of atom-linter, so reporting in both places: https://github.com/AtomLinter/linter-pylint/issues/201

**Comment by steelbrain** [comment] 2017-03-18 10:07
Hi @marmistrz 

There is no intended scan of the whole project in this package itself, can you provide `linter:debug` details? Also can you downgrade your linter version temporarily to see if the problem persists?

**Comment by marmistrz** [comment] 2017-03-21 10:48
```
Platform: linux
Atom Version: 1.15.0
Linter Version: 2.1.0
All Linter Providers: 
  - gfortran
  - Pylint
Matching Linter Providers: 
  - Pylint
Disabled Linter Providers; 
Current File scopes: 
  - *
  - source.python
  - meta.function-call.python
```

I'll try downgrading in a while.
This is how many pylints are spawned:
```
13398 marcin    20   0  102,4m  26,9m  32,2  0,3   0:01.75 R pylint                                                                                                                                            
13388 marcin    20   0  122,6m  38,8m  28,9  0,5   0:02.43 R pylint                                                                                                                                            
 1569 marcin    20   0 2705,4m 854,3m  28,3 10,8   6:13.34 R firefox                                                                                                                                           
13379 marcin    20   0  130,5m  46,8m  26,3  0,6   0:03.99 R pylint                                                                                                                                            
13386 marcin    20   0  123,3m  39,4m  26,3  0,5   0:02.44 R pylint                                                                                                                                            
13387 marcin    20   0  120,9m  37,0m  26,3  0,5   0:02.27 R pylint                                                                                                                                            
13407 marcin    20   0   84,7m  23,2m  25,7  0,3   0:00.95 R pylint                                                                                                                                            
13406 marcin    20   0   84,8m  22,9m  24,3  0,3   0:00.93 R pylint                                                                                                                                            
 5920 marcin    20   0 2620,0m  86,2m  23,0  1,1   7:21.10 S VBoxHeadless                                                                                                                                      
13380 marcin    20   0  130,5m  46,9m  22,4  0,6   0:03.86 R pylint                                                                                                                                            
 3836 marcin    20   0 1505,9m 346,8m  21,7  4,4   3:03.25 R electron                                                                                                                                          
13400 marcin    20   0   85,1m  23,6m  21,1  0,3   0:01.33 R pylint                                                                                                                                            
13385 marcin    20   0  119,9m  35,9m  19,7  0,5   0:02.12 R pylint    
```

**Comment by Arcanemagus** [comment] 2017-03-22 22:16
@marmistrz Downgrade _linter_, not `pylint` 😛

```bash
apm install linter@1.11.23
```

**Comment by Arcanemagus** [comment] 2017-03-22 22:17
Note that this looks like it is a duplicate of #1373.

**Comment by steelbrain** [comment] 2017-04-10 11:53
Fixed as of https://github.com/steelbrain/atom-linter/issues/160

**Closed by steelbrain** 2017-04-10 11:53 UTC
Labels: unconfirmed bug

**Comment by Arcanemagus** [comment] 2017-04-10 16:10
Well, _able_ to be fixed as of that 😛.

**Comment by steelbrain** [comment] 2017-04-10 16:13
@Arcanemagus but, that's all that's in my power so that's why I closed it 😛
