### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by vitaly-krugl** [steelbrain/linter#1168] opened 2016-06-01 21:47 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/vkruglikov/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/vkruglikov/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:00.6.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "linter": {
    "errorPanelHeight": 165
  }
}
```

### Installed Packages

```coffee
# User
linter, v1.11.4
linter-eslint, v7.2.2
react, v0.15.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-06-01 21:48
Dupe of #1054

**Closed by steelbrain** 2016-06-01 21:48 UTC
