### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by sq6jnx** [steelbrain/linter#1170] opened 2016-06-07 08:21 UTC
When pasting about a dozen of lines:

```
Uncaught Error: Cannot decorate a destroyed marker

/usr/share/atom/resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/usr/share/atom/resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/share/atom/resources/app.asar/src/text-editor.js:1400:33)
    at LinterViews.renderBubble [as _renderBubble] (/home/msadowsk/.atom/packages/linter/lib/linter-views.js:86:43)
    at /home/msadowsk/.atom/packages/linter/lib/helpers.coffee:23:18
```

If I missed something please ask.

(sidenote: clicking "Create issue on the linter package" from atom ends with "This page is taking way too long to load." on github)

**Comment by steelbrain** [comment] 2016-06-07 08:21
Dupe of #1054

**Closed by steelbrain** 2016-06-07 08:21 UTC
