### ISSUE TITLE
Black box when hovering over footer

### ISSUE THREAD

**Issue by Eldair** [steelbrain/linter#1501] opened 2017-06-22 15:16 UTC
Hello,

There is a strange box showing up above footer and behind bottom panel toggle button only while bottom panel has not been open since the session started. Sometimes it is not entirely black but rather replicates (cropped) part of the footer itself.

atom ver. 1.19.0-beta-1
OS windows 10 latest update

![atom bug bottom](https://user-images.githubusercontent.com/470003/27441652-7afcde50-576e-11e7-9c6c-26c00c0d875e.jpg)

**Comment by steelbrain** [comment] 2017-06-22 15:32
You have a messed up theme, please try with a builtin theme instead

**Comment by Arcanemagus** [comment] 2017-06-22 15:44
Duplicate of https://github.com/steelbrain/linter-ui-default/issues/344, which seems to be an issue in the Atom beta builds currently that is triggered by some third party themes (I've only seen it with Atom Material UI).

**Closed by Arcanemagus** 2017-06-22 15:44 UTC

**Comment by Eldair** [comment] 2017-06-22 16:52
Thanks for the info, couldn't find that other issue

**Comment by Arcanemagus** [comment] 2017-07-03 17:32
As an FYI, turns out that I'd only imagined that issue already being filed, so I filed https://github.com/atom/atom/issues/14915 to get this fixed in Atom.
