### ISSUE TITLE
Make linter result table rows clickable

### ISSUE THREAD

**Issue by fsievers** [steelbrain/linter#1380] opened 2017-03-20 06:42 UTC
If a linter shows errors, the table with shows wide lines but only the 'Line' column is clickable to jump to the error in the source file.
I think for usability, it would be much better if the whole row is clickable and gets you to the line with the error/warning.

**Comment by steelbrain** [comment] 2017-03-20 07:00
Dupe of https://github.com/steelbrain/linter-ui-default/issues/217

**Closed by steelbrain** 2017-03-20 07:00 UTC
