### ISSUE TITLE
Linter window opens again on click instead of going to line

### ISSUE THREAD

**Issue by gniezen** [steelbrain/linter#1490] opened 2017-06-14 09:20 UTC
When clicking on a linter error to jump to the corresponding line, the linter window just opens again instead:

![jun-14-2017 10-13-51](https://user-images.githubusercontent.com/418233/27124875-5d59e7f6-50ea-11e7-8f98-1670fa13a64e.gif)

#### Details
- linter 2.1.4, linter-ui-default 1.6.1, linter-eslint 8.2.1
- Atom 1.17.2
- MacOS El Capitan
- No errors logged in dev tools

**Comment by sualko** [comment] 2017-06-14 13:26
Same here on Ubuntu 16.04.

**Comment by cdokolas** [comment] 2017-06-14 14:40
Same here on Windows 10.

I get the feeling linter looses the linting context, (i.e. the window/pane with the code to be "linted") when it gets focus and thinks its own window is the new context (which can't be "linted", so the list switches to an empty list).

**Comment by Arcanemagus** [comment] 2017-06-14 16:44
This is possibly a duplicate of https://github.com/steelbrain/linter-ui-default/issues/349, in any case though as it deals with the UI it should be filed over there as this package no longer contains the UI code.

**Closed by Arcanemagus** 2017-06-14 16:44 UTC

**Comment by gniezen** [comment] 2017-06-20 12:24
This was indeed an issue with Linter itself, as it's now fixed in Linter 2.2.0 on Atom 1.18.0.
