### ISSUE TITLE
Implement language server protocol

### ISSUE THREAD

**Issue by marionebl** [steelbrain/linter#1270] opened 2016-11-20 10:38 UTC
Currently each linter provider has to implements its own approach to put work off Atoms main thread. In most cases this happens using "workers" `require('child_process').fork`, which introduces a lot of subtle edge cases and bugs. 

To address this I propose to implement the worker approach via a centralized utility provided by atom-linter. An approach with possible interop to other editor eco systems is the [language server protocol](https://github.com/Microsoft/language-server-protocol) used by Microsoft's VSCode.

I'm not sure about the exact matters of interfacing between the providers and the utility, though.

---
Related:
* https://github.com/sindresorhus/atom-linter-xo/pull/46
* https://github.com/sindresorhus/atom-linter-xo/issues/42

**Comment by steelbrain** [comment] 2016-11-20 10:45
Hi @marionebl 

The idea sounds nice, but as a side note We are using [`process-communication`](https://www.npmjs.com/package/process-communication) in `linter-eslint` and it seems to be working great.

Another side note is that Node.js by design is async, so unless you are doing a LOT of sync work on the thread you shouldn't have any issue. For example, most of the linters spawn external processes so the heavy work is offloaded to other processes by default but Node.js linter providers default to running in the main thread.

Also Atom has a built-in [Tasks](https://atom.io/docs/api/latest/Task) API that someone could use to achieve this purpose.

**Comment by marionebl** [comment] 2016-11-20 11:02
Hi @steelbrain,

Thank you for the fast reply and the suggestions on how to solve this in the current Atom environment. 

What do you think about the possible interop with stuff from the extended VSCode ecosystem?

**Comment by sindresorhus** [comment] 2016-11-20 11:11
> The idea sounds nice, but as a side note We are using process-communication in linter-eslint and it seems to be working great.

Sure, but I'm kinda hoping for a higher-level abstraction built into the API of Linter, so every linter doesn't have to write so much boilerplate.

> Also Atom has a built-in Tasks API that someone could use to achieve this purpose.

Interesting. I didn't know about that API. Any reason you're not using it in `linter-eslint`?

**Comment by steelbrain** [comment] 2016-11-20 11:18
The main reason `linter-eslint` is not using it is that we were unaware of the API at the time of writing and haven't had reason to move away yet

@marionebl Interop is actually pretty difficult. and having a full boiler plate won't be easy either, the closest is a github repo that people can fork and fill in. As this task is a little too complicated for a few helper functions.

For example, You cannot pass `textEditor` to the worker and do `textEditor.getBuffer()` or `textEditor.getText()` from the worker. You have to pass all of these params as literals

**Comment by Arcanemagus** [comment] 2016-11-20 20:17
I actually have a branch of `linter-stylelint` modified to use the Task API. The biggest problem with it is that many linters take a while to initialize on their first run (1-1.5 seconds!), and the Task API doesn't work very well for long running tasks (it's essentially impossible to end them properly, you just have to leave them running forever and trust Atom to close them when it exits).

**Comment by joeroback** [comment] 2016-11-28 01:18
for [atom-clang](https://github.com/joeroback/atom-clang), in order to lint, libclang needs to be able to run over the buffer, which is expensive (could be very expensive depending on how complex the c++ is). libclang parsing is also needed to provide code completions. atom-clang does it parsing via [AsyncWorker](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#api_nan_async_worker) from [NAN](https://github.com/nodejs/nan) (which uses libuv library built into Atom) and javascript Promises.

so really i have been waiting for a better push API because atom-clang already has to parse the file continuously to provide completions (out of the main Atom event loop/thread), i just want to be able to push diagnostics to the linter that come with the action of parsing for completions. i would not want some sort of massive IPC mechanism for linting separately. in fact, i wish linter would go on a diet, IMHO.

btw, I know of the Indie API, but since it does not provide file scope, i would have to maintain a window-level map of files -> diagnostics and push those every time, which i feel is kinda what the linter should be responsible for. i think this is coming in v2? but i unsure of the roadmap.

**Comment by steelbrain** [comment] 2016-11-28 15:43
@joeroback We support file-based indie linters in v2

As an update, I have an API in mind for spawning child threads for use in linter providers. I'll be posting it soon

**Comment by steelbrain** [comment] 2017-04-27 08:06
Good news everyone! The Atom core team has started working towards [LanguageServer integration in Atom](https://github.com/atom?utf8=%E2%9C%93&q=languageserver&type=&language=). Tho it's far from complete but is at least something.

I'm going to close this issue in this repository, feel free to continue discussing

**Closed by steelbrain** 2017-04-27 08:06 UTC
