### ISSUE TITLE
Hints not hiding when typing.

### ISSUE THREAD

**Issue by mikebronner** [steelbrain/linter#1472] opened 2017-05-23 17:26 UTC
Love the newly updated format! One thing I noticed is that the linter hints are no longer bring hidden when typing starts. This frequently causes the hint to overlay the text I'm typing, causing me to repeatedly move the mouse cursor to get the hint away from the line I am typing on.

I noticed in the settings there is a "Lint on Change" setting, which is checked. What do you thin about adjusting this behavior to lint when typing ceases, but hide the hint while actively typing?

**Comment by Arcanemagus** [comment] 2017-05-23 17:29
I _think_ this is a duplicate of https://github.com/steelbrain/linter-ui-default/issues/330, if you don't think that covers what you are thinking of here, then please file a new issue on the `linter-ui-default` repo as this package itself no longer has any interface.

**Closed by Arcanemagus** 2017-05-23 17:29 UTC

**Comment by mikebronner** [comment] 2017-05-23 17:30
Indeed! Thanks for the advice. :)
