### ISSUE TITLE
I have error when using linter in PHP file

### ISSUE THREAD

**Issue by Komar45** [steelbrain/linter#1437] opened 2017-04-15 21:58 UTC
[Linter] Error running PHP
See Console for more info. (Open View -> Developer -> Toogle Developer Tools)

**Comment by steelbrain** [comment] 2017-04-15 21:59
Did you actually follow the instructions and checked your developer tools? :)

In either case, this belongs to linter-php. Closing as external. Also duplicate of https://github.com/steelbrain/linter/issues/1432

**Closed by steelbrain** 2017-04-15 21:59 UTC
Labels: external
