### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by AskYous** [steelbrain/linter#1144] opened 2016-04-27 17:02 UTC
[Enter steps to reproduce below:]

1. Using typescript, I typed `import * as VisibilityLevels from "./api/visibilityLevelsk";` There's a typo. When I take out the `k`, this error goes away.

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\mlgyshan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (C:\Users\mlgyshan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\mlgyshan\AppData\Local\atom\app-1.7.2\resources\app.asar\src\text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (C:/Users/mlgyshan/.atom/packages/linter/lib/linter-views.js:86:43)
    at file:///C:/Users/mlgyshan/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:50.6.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:50.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:49 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:49 linter:lint (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:37 linter:lint (atom-text-editor.editor.is-focused)
     -0:32.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:30.2.0 pane:split-down-and-copy-active-item (atom-text-editor.editor.is-focused)
  2x -0:30 linter:lint (atom-text-editor.editor.is-focused)
     -0:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.1.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.3.0 linter:lint (atom-text-editor.editor.is-focused)
  3x -0:02.7.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "linter": {
    "errorPanelHeight": 82
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.9.1
less-autocompile, v1.0.0
linter, v1.11.4
open-github-from-npm, v0.1.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-04-27 17:03
Dupe of #1054

**Closed by steelbrain** 2016-04-27 17:03 UTC
