### ISSUE TITLE
I cannot tell what the problem is but the linter seems to be broken.

### ISSUE THREAD

**Issue by emvaldes** [steelbrain/linter#1438] opened 2017-04-22 01:35 UTC
I have no idea of what is going on but it used to work (very well).
Right now, all I can see is that the linter panel (bottom left corner) is just three 0 0 0 and nothing get's identified as a problem no matter what I do.
![screen shot 2017-04-21 at 6 34 47 pm](https://cloud.githubusercontent.com/assets/1084551/25300307/467940e8-26c1-11e7-9761-1577b9422519.png)

**Comment by steelbrain** [comment] 2017-04-22 03:14
Hi @emvaldes 

Can you please post a screenshot of your configuration of `linter` and `linter-ui-default` packages? Thank You!

**Comment by grgcnnr** [comment] 2017-05-18 01:49
Possibly related, sorry if I'm turning this into a general "linter isn't working thread :)"
I'm finding Linter goes dead quiet when Enabling the atom-silverstripe package, specifically the bit where it adds it's many, many syntaxes.

https://github.com/gorriecoe/atom-silverstripe/issues/6

**Comment by steelbrain** [comment] 2017-05-18 02:42
Hi @grgcnnr

Thanks for actually providing useful debug information, a pretty rare scene around here 😛 
As you can see the `Matching Linter Providers` list is empty. There's several reasons as to why that may be the case

- You have not installed the grammar for the file you want to execute on
- The linter provider doesn't recognize the grammar presented
- Some package is messing up the grammar, which seems to be the case with `source.css.scss.ssf_3-0_.ssf_3-0_3-9.ssf_3-1_.ssf_3-2_.fp_2.lnkfl_1.tagfl_1.gridfl_1`

A good normal grammar looks like `source.css.sccs source.css.ssf ...`

**Comment by grgcnnr** [comment] 2017-05-18 02:45
Yeah, pretty sure the issue is with atom-silverstripe. Ta.

**Comment by aminya** [comment] 2020-09-29 08:34
Closing as it is not related to this package.

**Closed by aminya** 2020-09-29 08:34 UTC
Labels: unconfirmed bug
