### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by IcebergRage** [steelbrain/linter#1141] opened 2016-04-25 15:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Users/Gura/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Users/Gura/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Users/Gura/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/Gura/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/Gura/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:03.8.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
linter, v1.11.4
linter-jshint, v2.1.0
minimap, v4.22.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-04-25 16:22
Dupe of #1054

**Closed by steelbrain** 2016-04-25 16:22 UTC
