### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by tosscaster** [steelbrain/linter#1154] opened 2016-05-19 04:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At C:\Users\bslee\AppData\Local\atom\app-1.7.3\resources\app.asar\src\display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (C:\Users\bslee\AppData\Local\atom\app-1.7.3\resources\app.asar\src\display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\bslee\AppData\Local\atom\app-1.7.3\resources\app.asar\src\text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (C:/Users/bslee/.atom/packages/linter/lib/linter-views.js:86:43)
    at file:///C:/Users/bslee/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:36 tabs:split-right (div.title)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.10.1
json-colorer, v0.3.0
linter, v1.11.4
linter-eslint, v7.2.2
react, v0.15.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-05-19 16:42
Duplicate of #1054.

**Closed by Arcanemagus** 2016-05-19 16:42 UTC
Labels: duplicate
