### ISSUE TITLE
`severity`, not `type` field should decide the color of the lint

### ISSUE THREAD

**Issue by oli-obk** [steelbrain/linter#1149] opened 2016-05-08 09:48 UTC
Currently, even if the severity field is set to `error`, but the `type` field is not anything linter knows, the lint is colored white (like an `info` I guess).

According to [the docs](https://github.com/steelbrain/linter/wiki/Linter-API#messages) The `type` is just the text displayed to the user, and should not have any effect on rest of the message

also, the squiggly lines below the text range disappear if the `type` is not `error` or `warning`

**Comment by steelbrain** [comment] 2016-05-08 12:54
That attribute is pretty new, also this is a dupe of https://github.com/steelbrain/linter-ui-default/issues/59

**Closed by steelbrain** 2016-05-08 12:54 UTC
