### ISSUE TITLE
feature request: Separate Lint on Change Intervals for reporting errors and clearing errors

### ISSUE THREAD

**Issue by skylize** [steelbrain/linter#1531] opened 2017-08-20 21:56 UTC
When typing a new bit of code, I often cannot help but to pause intermittently while my brain works out exactly what I want to write. The linter is very quick to jump up and remind me that my unfinished thought is of course not yet valid. This is quite distracting and often very much in the way (such as covering up a variable name I was looking at).

So I try increasing the Lint on Change Interval, but then of course after fixing a typo, there is a painful delay before the linter finally tells me my correct code is valid.

It would be sooooo much nicer if I could set 2 separate intervals: a long 1500ms delay for reporting invalid code and a short 100ms delay for clearing out the display when everything is valid. This would make live linting much less intrusive.

**Comment by steelbrain** [comment] 2017-08-20 22:53
You could disable lintsOnChange and then it'll be very less intrusive and only lint again on saves, does that solve your issue?

**Comment by skylize** [comment] 2017-08-22 01:38
No, that doesn't help. Live linting is good and useful. It's just that no matter what interval I set it at, it's always either a bit too intrusive (popping up during brief pauses) or a bit too slow (I have to stop and wait for linter to agree with me). 

My experience is that:
1. Usually when it seems intrusive I am trying to type something and I already know it's not right yet.
2. Usually when it seems slow I finished a correction and am waiting for the green light to move on. 

That's why I proposed separate intervals for showing vs hiding errors. I think it would eliminate the need for a balancing act on the 1 interval currently provided.

**Comment by skylize** [comment] 2017-08-28 01:16
Hmmm. No idea how # 1525 got in my clipboard. I meant to say I think this is duplicate of #1236.

**Comment by metalpapa** [comment] 2017-08-29 05:09
same error

**Comment by Arcanemagus** [comment] 2017-08-29 16:43
https://github.com/steelbrain/linter-ui-default/pull/427 should have fixed the tooltip showing up in the middle of typing which seems to be your primary problem here. Can you update to `linter-ui-default@1.6.8` and see if this is good enough for your purposes?

This is definitely a clearer explained duplicate of #1236 😉. That issue is a bit more extreme though as they don't want the issues to show _anywhere_ until their secondary delay has passed. 😕

----

@metalpapa There is no error talked about in this issue, so I'm not sure what your problem is. Please file a new issue if you are having an error, or follow #1236 if you are looking for what this issue was requesting.

**Comment by Arcanemagus** [comment] 2017-08-29 16:44
Duplicate of #1236

**Closed by Arcanemagus** 2017-08-29 16:44 UTC
Labels: feature request
