### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by DmintBreeze** [steelbrain/linter#1152] opened 2016-05-14 21:49 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/donna/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/donna/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:41.1.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:34.6.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
  2x -0:34.4.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:14.5.0 pane:split-down-and-copy-active-item (atom-text-editor.editor.is-focused)
  5x -0:14.3.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.9.1
autoclose-html, v0.23.0
linter, v1.11.4
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-05-14 21:50
Dupe of #1054

**Closed by steelbrain** 2016-05-14 21:50 UTC
