### ISSUE TITLE
Atom started flickering after linter update

### ISSUE THREAD

**Issue by galgalesh** [steelbrain/linter#1372] opened 2017-03-16 15:50 UTC
After the last linter update, the Atom UI started flickering. Each Time I change a python a code file with errors, the UI flickers a bit.

I have no idea how to start to debug this so let me know if you need more information.

- no js errors
- Ubuntu 16.04, Atom 1.15.0 (from webupd8 ppa)
- latest version of linter + pylint

**Comment by Arcanemagus** [comment] 2017-03-16 19:12
Can you define "flickers" a bit more? Are things moving around (for example, the panel appearing)? Or is it flashing as if there is a graphics driver bug?

**Comment by galgalesh** [comment] 2017-03-17 08:57
Flashing as if there is a graphics driver bug.

I'm using Intel graphics with the default Ubuntu drivers BTW.

**Comment by galgalesh** [comment] 2017-03-17 09:31
So, I did some further digging and debugging.

 - Flickering stops when I disable `linter`.
 - This seems to be an issue of [Chrome/Chromium + Ubuntu + Intel Xorg driver](https://bugs.chromium.org/p/chromium/issues/detail?id=606152#c73) + new version of linter. (Atom uses Electron which uses Chromium)
 - Removing the Intel Xorg driver (force falback to modesetting driver) fixes the issue!

```bash
sudo apt-get purge xserver-xorg-video-intel
# and reboot
```

This shouldn't cause any problems. [Newer Ubuntu & Debian releases drop the Intel xorg driver because of its poor quality](https://phoronix.com/scan.php?page=news_item&px=Ubuntu-Debian-Abandon-Intel-DDX).

PS: *It might be best to leave this issue open for other affected people. A lot of people seem to have this issue.*

**Comment by steelbrain** [comment] 2017-03-17 11:17
Thanks for the good find @galgalesh 

I wonder if you can just disable GPU on Atom to avoid uninstalling the driver (`atom --disable-gpu` or just `atom --enable-gpu-rasterization`)

**Comment by jy95** [comment] 2017-03-17 11:27
I have same issue with api-workbench that use linter :  https://atom.io/packages/api-workbench .
+ Windows 10 X64  
+ Atom 1.15.0

**Comment by steelbrain** [comment] 2017-03-17 11:30
Hi @Jy95

Can you report what you saw in the console?

**Comment by jy95** [comment] 2017-03-17 12:46
I cannot reproduce now : seems the extra installation for linter dependencies fix this message

**Comment by steelbrain** [comment] 2017-04-05 18:58
Closing because it's a driver issue

**Closed by steelbrain** 2017-04-05 18:58 UTC

**Comment by flamein** [comment] 2017-10-10 08:32
It's not just Xorg, i have the same thing on Fedora with wayland (maybe uses Xwayland)

**Comment by NeetishRaj** [comment] 2017-12-26 10:30
HTML file tabs in editor flickers in short bursts, whenever text is entered , it started happening when i installed **linter-htmlhint 1.4.0** plugin 
atom version is 1.21.0

**Comment by Arcanemagus** [comment] 2017-12-28 20:07
@NeetishRaj Please read the rest of the comments on this issue, this is a driver bug in the Intel drivers on Linux.
