### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by deterok** [steelbrain/linter#1105] opened 2016-03-23 08:19 UTC
[Enter steps to reproduce below:]

I don't know what i have done.

**Atom Version**: 1.6.0
**System**: "Gentoo Base
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/local/share/atom/resources/app.asar/src/display-buffer.js:1052

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/usr/local/share/atom/resources/app.asar/src/display-buffer.js:1052:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/local/share/atom/resources/app.asar/src/text-editor.js:1315:33)
    at LinterViews.renderBubble [as _renderBubble] (/home/deterok/.atom/packages/linter/lib/linter-views.js:86:43)
    at /home/deterok/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:34.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:34.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  6x -0:33.6.0 window:focus-next-pane (atom-text-editor.editor.is-focused)
     -0:25.1.0 window:focus-previous-pane (atom-text-editor.editor.is-focused)
     -0:23.5.0 window:focus-next-pane (atom-text-editor.editor.is-focused)
     -0:20 window:focus-pane-on-right (atom-text-editor.editor.is-focused)
     -0:18.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:16.6.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:15.2.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:13.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:12.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:09.3.0 window:focus-next-pane (atom-text-editor.editor.is-focused)
     -0:03.3.0 window:focus-previous-pane (atom-text-editor.editor.is-focused)
 36x -0:01.4.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "python-autopep8",
      "preview-plus"
    ]
  },
  "linter": {
    "errorPanelHeight": 164,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.8
atom-beautify, v0.28.26
atom-jinja2, v0.5.0
autocomplete-go, v1.0.4
autocomplete-python, v1.7.2
environment, v1.2.0
git-plus, v5.13.0
go-config, v1.1.2
go-get, v1.0.1
go-plus, v4.0.1
go-quick-import, v0.2.0
gofmt, v1.1.2
gometalinter-linter, v1.0.4
gorename, v1.0.0
language-restructuredtext, v0.12.0
linter, v1.11.4
linter-python, v2.1.3
minimap, v4.21.0
navigator-godef, v1.0.2
python-autopep8, v0.1.3
python-tools, v0.6.7
rest-client, v1.0.0
seti-icons, v0.4.5
terminal-plus, v0.14.5
tester-go, v1.0.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-03-23 09:10
Dupe of #1054

**Closed by steelbrain** 2016-03-23 09:10 UTC
