### ISSUE TITLE
linter-flask8 doesn't work 

### ISSUE THREAD

**Issue by miketheknight12** [steelbrain/linter#1606] opened 2019-01-13 02:57 UTC
when I use atom no errors show up 
please help!

<img width="1440" alt="screen shot 2019-01-12 at 9 55 38 pm" src="https://user-images.githubusercontent.com/9868419/51081063-f2815f80-16b4-11e9-87c8-3a75e74abb36.png">

**Comment by caleb531** [comment] 2019-01-13 04:53
@miketheknight12 Same here, except I'm using `linter-flake8`. The Linter panel never shows and the status indicators indicate zero errors/warnings (even though they most certainly do, judging from the code).

**Comment by miketheknight12** [comment] 2019-01-13 06:12
@caleb531  so is there nothing that can be done about it :(

**Comment by miketheknight12** [comment] 2019-01-13 07:46
@scottbert then should I install an older version?

**Comment by scottbert** [comment] 2019-01-13 07:50
I got linters working again by turning off auto updates (if you have that plugin enabled), manually removing the new linter package (command line `apm remove linter`) and then installing the old one manually (`apm install linter@2.2.0`)

**Comment by miketheknight12** [comment] 2019-01-13 07:53
@scottbert it says command line apm: is not found 
<img width="1440" alt="screen shot 2019-01-13 at 2 53 09 am" src="https://user-images.githubusercontent.com/9868419/51082915-684df100-16de-11e9-87f5-66067ee22fc7.png">

**Comment by scottbert** [comment] 2019-01-13 07:55
https://discuss.atom.io/t/apm-command-not-found/7207

**Comment by miketheknight12** [comment] 2019-01-13 07:59
@scottbert thank you that helped. However flake still refuses to work
[Linter] Error running Flake8
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

**Comment by scottbert** [comment] 2019-01-13 08:01
You have to quit atom before doing the apm stuff - when you restart atom, go to prefs => packages and verify that linter is v 2.2.0 - if you did all this and can see linter is v 2.2.0 then I'm not sure I can help - these steps worked for me to get linter-sass-lint working.

**Comment by miketheknight12** [comment] 2019-01-13 08:05
@scottbert yes I did, unfortunately, the problem is the same. I appreciate the help though, thank you!
<img width="1440" alt="screen shot 2019-01-13 at 3 05 20 am" src="https://user-images.githubusercontent.com/9868419/51083009-1908c000-16e0-11e9-841c-b13b4b59853d.png">

**Comment by Arcanemagus** [comment] 2019-01-14 18:53
@miketheknight12 the full information should be in the console (as the error message is telling you), however _usually_ this is due to not having `flake8` available in your `$PATH`. If you are still having issues after checking that please file an issue on `linter-flake8`.

**Comment by miketheknight12** [comment] 2019-01-14 18:57
@Arcanemagus  um this is what when using terminal 
<img width="1440" alt="screen shot 2019-01-14 at 1 57 11 pm" src="https://user-images.githubusercontent.com/9868419/51134000-5a928b80-1804-11e9-8751-b40eac0a2481.png">

**Comment by Arcanemagus** [comment] 2019-01-14 18:58
I've filed issues on all the AtomLinter providers that are affected by the removal of the v1 API in v2.3.0, please follow the relevant issues there.

I'm going to close this issue here as it isn't a bug in `linter` (just a release that should have been a major one).

**Closed by Arcanemagus** 2019-01-14 18:58 UTC

**Comment by miketheknight12** [comment] 2019-01-14 18:59
@Arcanemagus ok when can i see a fix to this issue ?

**Comment by caleb531** [comment] 2019-01-14 19:01
@miketheknight12 The Extraneous Whitespace issue can be fixed by upgrading to flake8 3.6.0. See:
https://github.com/PyCQA/pycodestyle/issues/728

**Comment by Arcanemagus** [comment] 2019-01-14 19:01
@miketheknight12 The version of `pycodestyle` bundled with your version of `flake8` doesn't include support for Python 3.7 yet: https://github.com/PyCQA/pycodestyle/issues/728. You should be using Python 3.6, or upgrading to the latest version of `flake8` if they are supporting a new enough version of `pycodestyle` there yet.

For `linter-flake8` itself you should follow https://github.com/AtomLinter/linter-flake8/issues/665.

**Comment by miketheknight12** [comment] 2019-01-14 19:02
@Arcanemagus the thing is, I have the lastest version for flake8. But am using pthon 2.7 .10

**Comment by miketheknight12** [comment] 2019-01-14 19:03
@Arcanemagus is due to the fact that I'm using python 2.7.10?

**Comment by Arcanemagus** [comment] 2019-01-14 19:04
Your screenshot shows you are running Python 3.7, not 2.7.10. If you _are_ using Python 2.7.10, it's loading the libraries from 3.7.

**Comment by miketheknight12** [comment] 2019-01-14 19:05
@Arcanemagus  yeah for some odd reason its doing that, but the version being used is 2.7.10. Would that be a problem?

**Comment by miketheknight12** [comment] 2019-01-14 19:06
@Arcanemagus 
<img width="1440" alt="screen shot 2019-01-14 at 2 05 43 pm" src="https://user-images.githubusercontent.com/9868419/51134422-87936e00-1805-11e9-92ed-fa42cc4ee669.png">

**Comment by Arcanemagus** [comment] 2019-01-14 19:08
Considering you are getting errors, I would say so 😉. You need to get `flake8` working in the first place before you can use it in anything else.

As your screenshot shows although `python --version` is showing 2.7.10, `flake8 --version` is showing that it is using Python 3.7.2.

You'll need to find a support avenue for `flake8` to get that figured out as that has nothing to do with `linter` (_or_ `linter-flake8`). From the little I know of macOS I'm guessing you have conflicting versions from the system `python` and the one installed by `brew`, but I don't know how you would fix that.

**Comment by miketheknight12** [comment] 2019-01-14 19:11
@Arcanemagus yeah I just started using python so im not too sure how to go about fixing this. Should i just reinstall python?

**Comment by caleb531** [comment] 2019-01-16 19:01
@miketheknight12 FWIW, linter-flake8 2.4.0 was just released, and I can confirm that flake8 errors are now correctly displaying again in Atom (under linter 2.3.0). So try updating the linter-flake8 package from within Atom (and maybe reload Atom for good measure), and you should be good to go.

**Comment by miketheknight12** [comment] 2019-01-16 19:13
@caleb531 /Users/michael/.atom/packages/linter/lib/linter-registry.js:155 [Linter] Error running Flake8 Error: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
    at ChildProcess.<anonymous> (/Users/michael/.atom/packages/linter-flake8/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by miketheknight12** [comment] 2019-01-16 19:13
I keep getting the same stupid error :(
