### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by ehsan-khaliki** [steelbrain/linter#1311] opened 2017-02-07 00:06 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.0-beta3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [linter](https://github.com/atom-community/linter) package 1.11.21

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189

TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:189:34)
    at /app.asar/node_modules/text-buffer/lib/marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (/app.asar/node_modules/text-buffer/lib/marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (/app.asar/node_modules/text-buffer/lib/marker.js:269:18)
    at /packages/linter/lib/editor-linter.js:75:35
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at EditorLinter.deleteMessage (/packages/linter/lib/editor-linter.js:151:20)
    at /packages/linter/lib/linter-views.js:106:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/packages/linter/lib/linter-views.js:104:13)
    at LinterViews.render (/packages/linter/lib/linter-views.js:58:10)
    at /packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MessageRegistry.updatePublic (/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Non-Core Packages

```
atom-monokai 0.10.7 
git-diff-details 1.4.0 
goto-definition 1.1.19 
highlight-selected 0.12.0 
linter 1.11.21 
linter-eslint 8.1.0 
linter-rubocop 0.5.3 
linter-ruby 1.2.4 
minimap 4.26.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
ruby-block 0.3.6 
seti-icons 1.3.4 
split-diff 1.1.1 
```

**Comment by steelbrain** [comment] 2017-02-07 00:08
Dupe of https://github.com/steelbrain/linter-ui-default/issues/41
bug in Atom

**Closed by steelbrain** 2017-02-07 00:08 UTC
