### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMarker' of undefined

### ISSUE THREAD

**Issue by Gozala** [steelbrain/linter#1209] opened 2016-07-27 17:22 UTC
[Enter steps to reproduce below:]

I get this fairly often lately when using with flow based projects. Don't really have a specific steps to reproduce I'm afraid:

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.6
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.14
### Stack Trace

Uncaught TypeError: Cannot read property 'getMarker' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:194

TypeError: Cannot read property 'getMarker' of undefined
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:194:65)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1525:37)
    at /Users/gozala/.atom/packages/linter/lib/editor-linter.js:59:21
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/gozala/.atom/packages/linter/lib/editor-linter.js:143:20)
    at /Users/gozala/.atom/packages/linter/lib/linter-views.js:111:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/gozala/.atom/packages/linter/lib/linter-views.js:109:11)
    at LinterViews.render (/Users/gozala/.atom/packages/linter/lib/linter-views.js:58:10)
    at /Users/gozala/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/gozala/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/gozala/.atom/packages/linter/lib/message-registry.js:24:16)
```
### Commands

```
     -0:46.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:44 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:39.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  8x -0:36.3.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:29.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:28.7.0 core:cut (atom-text-editor.editor.is-focused)
     -0:27.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:27 core:paste (atom-text-editor.editor.is-focused)
     -0:26.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:06.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".flowconfig"
      ]
    },
    "disabledPackages": [
      "Tern",
      "language-lisp",
      "language-typescript",
      "nrepl",
      ".bin",
      "tabs",
      "linter-flow-plus",
      "ide-flow",
      "nuclide",
      "flow-ide",
      "standard-formatter"
    ],
    "followSymlinks": true,
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/Users/gozala/Projects/",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 125,
    "showErrorTabLine": true
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined (inactive)
advanced-open-file, v0.16.3 (inactive)
atom-beautify, v0.29.10 (active)
atom-pair, v2.0.10 (active)
atom-typescript, vundefined (active)
autocomplete-flow, v1.6.0 (active)
block-comment-plus, v0.4.0 (inactive)
busy-signal, v1.1.0 (active)
clipboard-plus, v0.5.1 (active)
copy-as-rtf, v0.9.3 (inactive)
git-history, v3.2.0 (inactive)
git-plus, v5.16.2 (inactive)
jscs-fixer, v1.1.1 (inactive)
language-babel, v2.32.1 (active)
language-clojure, v0.21.0 (active)
language-elm, v1.5.0 (active)
language-flatbuffers, v0.2.0 (active)
language-lisp, v0.2.0 (inactive)
language-racket, v0.4.0 (active)
language-scheme, v1.4.0 (active)
linter, v1.11.14 (active)
linter-flow, v5.4.0 (active)
merge-conflicts, v1.4.4 (active)
nrepl, v0.4.0 (inactive)
pain-split, v1.4.0 (active)
Parinfer, v1.15.0 (active)
project-manager, v2.9.7 (active)
recent-files-fuzzy-finder, v0.2.4 (active)
run-command2, v1.12.2 (inactive)
save-session, v0.16.0 (active)
set-syntax, v0.3.0 (active)
smart-tab-name, v1.0.5 (active)
standard-formatter, v2.0.1 (inactive)
tab-switcher, v1.5.3 (active)
Tern, v0.8.0 (inactive)
the-closer, v0.6.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)
```
# Dev

No dev packages

P.S.: Issue url generated exceeds limits of ngnix.

**Comment by steelbrain** [comment] 2016-07-27 17:30
This is weird, do you get it even after you restart Atom?
Also can you provide some repro steps for this?

**Comment by Gozala** [comment] 2016-07-27 17:45
> This is weird, do you get it even after you restart Atom?

Usually restarting just linter add-on fixes it.

> Also can you provide some repro steps for this?

I honestly don't know tend to happen more frequently since last few weeks, so I suspect there maybe something with new linter or flow version that causes this.

My other suspicion is that it maybe related to having same file being open in multiple panels.

My last guess is that it maybe related to flow server restarting.

**Comment by Gozala** [comment] 2016-07-27 17:45
I'll post steps to reproduce if I notice a pattern causing this.

**Comment by steelbrain** [comment] 2016-07-27 17:53
On a side note, I personally use `flow-ide` to manage my flow projects (and I also wrote it so), it's pretty stable. Can you try that and disable the current flow package you're using and see if you still see the error?
Also can you try Atom stable? It could be a bug in Atom itself since you're using the Beta

**Comment by Gozala** [comment] 2016-07-27 21:54
> On a side note, I personally use flow-ide to manage my flow projects (and I also wrote it so), it's pretty stable. Can you try that and disable the current flow package you're using and see if you still see the error?

I tend to get following error with **flow-ide** a lot and nothing in status indicator which is why I preferred using `linter-flow`:

```
Error: flow is rechecking; this should not take long [merging inference] -flow is rechecking; this should not take long [merging inference] \
Error: flow is rechecking; this should not take long [merging inference] -flow is rechecking; this should not take long [merging inference] \
    at ChildProcess.<anonymous> (/Users/gozala/.atom/packages/flow-ide/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:41:20)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

> Also can you try Atom stable? It could be a bug in Atom itself since you're using the Beta

Will do thanks.

**Comment by Arcanemagus** [comment] 2016-07-27 22:01
Btw, looks like this is similar or the same as https://github.com/steelbrain/linter-ui-default/issues/105.

**Comment by steelbrain** [comment] 2016-07-28 16:45
@Gozala If you get nothing with flow ide then it means you don't have a `.flowconfig`, which is a necessity for using full flow features. Otherwise it's just a syntax checker 😉

**Comment by Gozala** [comment] 2016-07-28 17:07
> @Gozala If you get nothing with flow ide then it means you don't have a .flowconfig, which is a necessity for using full flow features. Otherwise it's just a syntax checker 😉

I do have `.flowconfig`. What I meant is that your [busy-signal](https://github.com/steelbrain/busy-signal) icon isn't spinning while **flow-ide** is querying flow server.


On the other note maybe this issue is actually related to **linter-flow** package as I have not seen it when using **flow-ide**.

**Comment by steelbrain** [comment] 2016-07-28 17:09
Yeah `busy-signal` only spins if you run the `steelbrain/transition-towards-ide` branch with the latest linter-ui-default. These are the not-yet-released features.

Talking about the real bug, I think it's just an Atom issue as Landon (@Arcanemagus) also encountered it some time ago on the same beta you're using. Closing as Atom bug, feel free to keep discussing and reopen if this occurs with a stable versions

**Comment by Gozala** [comment] 2016-07-28 17:17
> Yeah busy-signal only spins if you run the steelbrain/transition-towards-ide of linter branch with the latest linter-ui-default. These are the not-yet-released features.

Hmm... Hmm I wonder how does **linter-flow** is taking advantage of it.

**Comment by Gozala** [comment] 2016-07-28 17:19
Created steelbrain/flow-ide#20 for the ether issue mentioned.

**Comment by steelbrain** [comment] 2016-07-28 17:24
I've fixed the flow-ide bug, but I am still curious as to how linter-flow does it because there's nothing indicating it in the source code. Are you on Atom slack?

**Comment by Gozala** [comment] 2016-07-28 17:29
> I've fixed the flow-ide bug, but I am still curious as to how linter-flow does it because there's nothing indicating it in the source code. Are you on Atom slack?

Never mind I think I may have being using my forked version that was adding busy-signal integration AtomLinter/linter-flow#93

**Comment by steveoh** [comment] 2016-08-02 17:51
I'll try to get a better grasp on when this occurs but for now I don't have a repro.

**Atom Version**: 1.9.0
**System**: Microsoft Windows Server 2012 R2 Standard
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.14


### Stack Trace

Uncaught TypeError: Cannot read property 'getMarker' of undefined

```
At C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\src\decoration-manager.js:194

TypeError: Cannot read property 'getMarker' of undefined
    at DecorationManager.module.exports.DecorationManager.decorateMarker (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\src\decoration-manager.js:194:65)
    at TextEditor.module.exports.TextEditor.decorateMarker (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor.js:1525:37)
    at C:/Users/agrc-arcgis/.atom/packages/linter/lib/editor-linter.js:59:21
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at EditorLinter.addMessage (C:/Users/agrc-arcgis/.atom/packages/linter/lib/editor-linter.js:143:20)
    at C:/Users/agrc-arcgis/.atom/packages/linter/lib/linter-views.js:111:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (C:/Users/agrc-arcgis/.atom/packages/linter/lib/linter-views.js:109:11)
    at LinterViews.render (C:/Users/agrc-arcgis/.atom/packages/linter/lib/linter-views.js:58:10)
    at file:///C:/Users/agrc-arcgis/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\agrc-arcgis\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.updatePublic (C:/Users/agrc-arcgis/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (C:/Users/agrc-arcgis/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:08.7.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:01.6.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "autocomplete-css",
      "autocomplete-html",
      "autosave",
      "background-tips",
      "bookmarks",
      "dev-live-reload",
      "exception-reporting",
      "git-diff",
      "go-to-line",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-source",
      "language-toml",
      "language-yaml",
      "package-generator",
      "welcome",
      "emmet",
      "atom-prettify",
      "format-sql",
      "formatter",
      "jscs-fixer",
      "about",
      "archive-view",
      "styleguide",
      "linter-stylint",
      "linter-jscs",
      "linter-jshint"
    ],
    "ignoredNames": [
      "*.pyc",
      ".coverage",
      "*.egg-info",
      ".eggs"
    ],
    "packagesWithKeymapsDisabled": [
      "case-switch"
    ],
    "themes": [
      "slack-ui",
      "atom-light-syntax"
    ]
  },
  "linter": {
    "lintDebug": false,
    "lintOnChangeInterval": 1000,
    "lintOnEditorFocus": true,
    "showErrorPanel": false,
    "showErrorTabFile": false,
    "showErrorTabLine": true,
    "showHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
advanced-open-file, v0.16.3 (inactive)
agrc-snippets, v0.1.0 (active)
amdbutler, v0.3.0 (inactive)
atom-prettify, v0.1.3 (inactive)
atom-typescript, v10.1.5 (active)
case-switch, v2.2.2 (active)
emmet, v2.4.3 (inactive)
eslint-fixer, v1.1.0 (active)
format-sql, v0.3.0 (inactive)
formatter, v2.12.3 (inactive)
highlight-selected, v0.11.2 (active)
jscs-fixer, v1.1.1 (inactive)
language-log, v1.5.0 (active)
linter, v1.11.14 (active)
linter-eslint, v7.2.4 (active)
linter-flake8, v1.13.2 (active)
linter-jscs, v4.0.5 (inactive)
linter-jshint, v2.1.0 (inactive)
linter-stylint, v2.2.2 (inactive)
merge-conflicts, v1.4.4 (active)
northem-light-atom-syntax, v0.19.1 (inactive)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
python-yapf, v0.11.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
slack-ui, v0.7.0 (active)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.3 (inactive)
Stylus, v3.0.0 (active)
tabs-to-spaces, v1.0.2 (active)
underline-trailing-whitespace, v1.4.0 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by tommyblue** [comment] 2016-08-04 08:26
It's happening since I upgraded to Atom 1.9.x (happens with 1.9.0, 1.9.1 and 1.9.2). To trigger it I can just split the windows (cmd+k+arrow) then close it
I'm on Mac 10.11.6

**Comment by steelbrain** [comment] 2016-08-04 22:29
Reopening based on discussion from #1210

**Comment by Arcanemagus** [comment] 2016-08-05 22:44
Is anyone able to reproduce this on v1.10..0-beta2? I'm with @davepeck in that it looks like this was related to https://github.com/steelbrain/linter/issues/1212 and might now be fixed.

**Comment by steelbrain** [comment] 2016-11-29 09:59
Closing based on above comment

**Closed by steelbrain** 2016-11-29 09:59 UTC
Labels: unconfirmed bug
