### ISSUE TITLE
Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by MichaelTSS** [steelbrain/linter#1134] opened 2016-04-18 13:12 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1346:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/michaeltresseras/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/michaeltresseras/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
     -0:12.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:11.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:11 core:select-up (atom-text-editor.editor.is-focused)
     -0:11 core:select-down (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:08.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:00.8.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:00.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ],
    "projectHome": "/Users/michaeltresseras/"
  },
  "linter": {
    "errorPanelHeight": 130
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.2
file-icons, v1.7.1
gulp-control, v0.4.5
linter, v1.11.4
linter-eslint, v7.2.0
linter-sass-lint, v1.3.1
minimap, v4.21.0
php-cs-fixer, v2.5.6
pigments, v0.26.0
project-manager, v2.9.7
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-04-18 13:12
Dupe of #1054

**Closed by steelbrain** 2016-04-18 13:12 UTC
