### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by BenLeggiero** [steelbrain/linter#1641] opened 2019-07-21 18:35 UTC
[Enter steps to reproduce:]

1. Open Atom
2. 💥

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.15
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/toggle-view.js:13:21)
    at /packages/linter/lib/toggle-view.js:10:37)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/main.js:8:39)
    at /packages/linter/lib/main.js:170:24)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/index.js:3:34)
    at /packages/linter/lib/index.js:100:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
highlight-selected 0.16.0 
intentions 1.1.5 
language-liquid 0.7.0 
linter 2.1.1 
linter-markdown 5.2.9 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
markdown-writer 2.11.7 
material-colors 0.1.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
one-dark-material-syntax 1.0.3 
scss-snippets 0.6.0 
Sublime-Style-Column-Selection 1.7.5 
tool-bar 1.1.12 
tool-bar-atom 1.7.0 
tool-bar-markdown 0.8.0 
tool-bar-markdown-writer 0.5.0 
```

**Comment by Arcanemagus** [comment] 2019-07-21 18:53
It looks like Atom failed to install all the dependencies for your installation, can you try re-installing the package?

**Comment by BenLeggiero** [comment] 2019-07-21 22:20
I tried opening the package in Atom's settings. I pressed Uninstall, and then I pressed Install. After installation, I got this error:

[Enter steps to reproduce:]

1. Install `linter`
2. 💥

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.15
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/toggle-view.js:13:21)
    at /packages/linter/lib/toggle-view.js:10:37)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/main.js:8:39)
    at /packages/linter/lib/main.js:170:24)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/linter/lib/index.js:3:34)
    at /packages/linter/lib/index.js:100:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3430498)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418632)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418410)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3416041)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418270)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418213)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381112)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:934678
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:929284)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1119363)
    at ChildProcess.o.process.on.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1119569)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -2:32.5.0 tree-view:duplicate (span.name.icon.icon-file-text)
     -2:27.9.0 core:confirm (input.hidden-input)
 19x -2:26.1.0 core:close (input.hidden-input)
     -2:03.0 core:save (input.hidden-input)
     -1:58.7.0 tree-view:duplicate (li.file.entry.list-item.status-added.selected)
     -1:50.4.0 core:confirm (input.hidden-input)
     -1:45.7.0 core:save (input.hidden-input)
     -0:35.4.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
highlight-selected 0.16.0 
intentions 1.1.5 
language-liquid 0.7.0 
linter 2.1.1 
linter-markdown 5.2.9 
linter-scss-lint 3.2.1 
linter-ui-default 1.7.1 
markdown-writer 2.11.7 
material-colors 0.1.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-quick-highlight 1.0.1 
minimap-selection 4.5.0 
one-dark-material-syntax 1.0.3 
scss-snippets 0.6.0 
Sublime-Style-Column-Selection 1.7.5 
tool-bar 1.1.12 
tool-bar-atom 1.7.0 
tool-bar-markdown 0.8.0 
tool-bar-markdown-writer 0.5.0 
```

**Comment by Aargonian** [comment] 2019-07-22 05:48
I am also receiving this error. Fresh install of atom, with the linter package plus every package I normally get all at once just installed.

[Steps to reproduce]

1. install Linter
2. open Atom

**Atom**: 1.38.2 x64
**Electron**: 4.2.6
**Node:** 10.11.0
**Chrome:** 69.0.3497.128
**OS**: "Manjaro Linux"
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:283:28)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter/lib/toggle-view.js:13:21)
    at /packages/linter/lib/toggle-view.js:10:37)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter/lib/main.js:8:39)
    at /packages/linter/lib/main.js:170:24)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/linter/lib/index.js:3:34)
    at /packages/linter/lib/index.js:100:2)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.17 
autocomplete-python 1.14.1 
ex-mode 0.18.0 
Hydrogen 2.10.3 
linter 2.1.1 
linter-pydocstyle 0.4.7 
linter-pylint 2.1.1 
linter-python-pep8 0.2.0 
minimap 4.29.9 
minimap-lens 0.2.0 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
platformio-ide-terminal 2.9.1 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
vim-mode-plus 1.36.0 
```

**Comment by Aerijo** [comment] 2019-07-22 11:16
@Aargonian FYI you are using an unofficial Atom build, so you won't get any support for any issues you encounter.

**Comment by Aargonian** [comment] 2019-07-22 13:40
@Aerijo I was unaware the Arch-based build was considered unofficial, as I got it from my distro's main repositories. I guessed it would be considered official enough, even based on the wording from that page, which doesn't seem to explicitly state that anything would be considered unoffocial.

I'll see if I can replicate the issue on a different system when I get the chance, then. My apologies.

**Comment by Aerijo** [comment] 2019-07-22 13:48
@Aargonian Yeah, others have been confused by Arch’s use of the word “official”, which I guess they mean as provided by Arch. The problem with these builds is that they often have altered components (e.g., your Electron version is two major releases too high), so issues you face with it may not even exist on the official builds. 

In this case, it may not help though, as the issue author appears to be on a normal build.

**Comment by BenLeggiero** [comment] 2019-08-07 20:11
I'm having this same issue again on another machine.

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1

**Comment by Aargonian** [comment] 2019-08-15 01:22
Alright, I said I'd replicate this on a different system and I've been very sidetracked since then. However! I did manage to replicate this issue on my Windows machine, where I was working on a totally different project and didn't realize I hadn't already installed Linter. This is the official Atom install, as installed from the x64 installer I got from the atom.io website for Windows 10.

[Enter steps to reproduce:]

1. Install Linter
2. Do Nothing Else

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter](https://github.com/steelbrain/linter) package 2.1.1


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'sb-config-file'

Error: Cannot find module 'sb-config-file'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/linter/lib/toggle-view.js:13:21)
    at /packages/linter/lib/toggle-view.js:10:37)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/linter/lib/main.js:8:39)
    at /packages/linter/lib/main.js:170:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:146719)
    at /packages/linter/lib/index.js:3:34)
    at /packages/linter/lib/index.js:100:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:1:712926)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3553046)
    at Package.activateNow (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3541030)
    at measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540808)
    at Package.measure (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3538418)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540668)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:3540611)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:11:381612)
    at /packages/build/node_modules/atom-package-deps/lib/index.js:36:35
    at Generator.next (<anonymous>)
    at step (/packages/build/node_modules/atom-package-deps/lib/index.js:66:191)
    at /packages/build/node_modules/atom-package-deps/lib/index.js:66:361
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Commands

```
     -1:44.1.0 core:confirm (input.hidden-input)
 28x -1:40.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
build 0.70.0 
busy-signal 2.0.1 
ex-mode 0.18.0 
language-batch 0.4.0 
linter 2.1.1 
minimap 4.29.9 
minimap-lens 0.3.0 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
platformio-ide-terminal 2.9.3 
todo-show 2.3.2 
vim-mode-plus 1.36.0 
```

**Comment by Redsandro** [comment] 2019-10-17 18:44
I'm also experiencing this, on atom `1.40.x` and `atom-beta 1.41.0-beta1`.
Linux Mint 19.2 x64.

After updating `linter` from 2.1.1 to 2.3.1, the problem is gone.

If anyone else can verify that linter works from version 2.3.1+ on atom 1.40+, we can close this issue.

**Comment by ekce** [comment] 2020-02-12 23:32
Updating fixed the issue for me as well.

**Comment by steelbrain** [comment] 2020-02-12 23:44
Closing based on above comments

**Closed by steelbrain** 2020-02-12 23:44 UTC
