### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMarker' of undefined

### ISSUE THREAD

**Issue by Anup-Allamsetty** [steelbrain/linter#1210] opened 2016-08-04 12:40 UTC
I am getting the following error, when I open my atom-editor: 

```
TypeError: Cannot read property 'getMarker' of undefined
  at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/decoration-manager.js:194:65)
  at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:1525:37)
  at /Users/anup/.atom/packages/linter/lib/editor-linter.js:83:22
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at EditorLinter.addMessage (/Users/anup/.atom/packages/linter/lib/editor-linter.js:160:22)
  at /Users/anup/.atom/packages/linter/lib/linter-views.js:158:24
  at Array.forEach (native)
  at LinterViews.notifyEditorLinters (/Users/anup/.atom/packages/linter/lib/linter-views.js:156:13)
  at LinterViews.render (/Users/anup/.atom/packages/linter/lib/linter-views.js:90:12)
  at /Users/anup/.atom/packages/linter/lib/linter.coffee:39:14
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at MessageRegistry.updatePublic (/Users/anup/.atom/packages/linter/lib/message-registry.js:118:20)
  at UpdateMessages (/Users/anup/.atom/packages/linter/lib/message-registry.js:35:17)
```

**Comment by steelbrain** [comment] 2016-08-04 12:49
Are you on Atom 1.9.x by any chance? Also what's your OS?

**Comment by Anup-Allamsetty** [comment] 2016-08-04 13:11
Atom version: 1.10.0-beta0
OS - Mac OS X El Capitan (version: 10.11.6)

**Comment by steelbrain** [comment] 2016-08-04 13:12
Atom beta is known to break Linter, idk why though. It's an Atom bug if I had to take a guess, can you repro it on a stable version?

**Comment by Anup-Allamsetty** [comment] 2016-08-04 13:17
Yes, I am able to reproduce it on the latest version of atom also. 

Current Atom (stable release) version: 1.9.2

**Comment by steelbrain** [comment] 2016-08-04 13:20
Can you provider some steps to repro? They will be very helpful as I'm on the same version and do not see the error

**Comment by Arcanemagus** [comment] 2016-08-04 18:45
This is a duplicate of #1209, you might want to just re-open that?

**Comment by steelbrain** [comment] 2016-08-04 22:30
Closed in favor of https://github.com/steelbrain/linter/issues/1209

**Closed by steelbrain** 2016-08-04 22:30 UTC
