### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by brucemackenzie** [steelbrain/linter#1127] opened 2016-04-12 22:23 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.4

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1052:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1315:33)
    at LinterViews.renderBubble [as _renderBubble] (/Users/bruce/.atom/packages/linter/lib/linter-views.js:86:43)
    at /Users/bruce/.atom/packages/linter/lib/helpers.coffee:23:18
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "jslint"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
linter, v1.11.4
linter-jshint, v2.0.4
pretty-json, v1.0.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-04-12 22:23
Dupe of #1054

**Closed by steelbrain** 2016-04-12 22:23 UTC
